
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * JFrameGUI class
 * @author Travis
 */
public class JFrameGUI extends javax.swing.JFrame {

    
    /**
     * Variables
     */
    
    /**
     *Create a clsLogic class object 
     */
    clsLogic clsLogic;
    
    /**
     * Create a clsAI class object
     */
    //clsAI clsAI;
    
    /**
     * Creates new form JFrameGUI
     */
    public JFrameGUI() {
        initComponents();
        clsLogic = new clsLogic();
        //clsAI = new clsAI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtField_20 = new javax.swing.JTextField();
        btnStart = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lblPlayer1Win = new javax.swing.JLabel();
        lblPlayer2Win = new javax.swing.JLabel();
        lblTie = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaGameStatus = new javax.swing.JTextArea();
        txtField_11 = new javax.swing.JTextField();
        txtField_10 = new javax.swing.JTextField();
        txtField_01 = new javax.swing.JTextField();
        txtField_02 = new javax.swing.JTextField();
        txtField_12 = new javax.swing.JTextField();
        txtField_22 = new javax.swing.JTextField();
        txtField_21 = new javax.swing.JTextField();
        txtField_00 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe");
        setResizable(false);
        setSize(new java.awt.Dimension(100, 100));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtField_20.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        txtField_20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtField_20.setToolTipText("");
        txtField_20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtField_20.setFocusable(false);
        txtField_20.setName("20"); // NOI18N
        txtField_20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLabel_Clicked(evt);
            }
        });
        getContentPane().add(txtField_20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 100, 100));

        btnStart.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        btnStart.setText("Start Game");
        btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStart_Clicked(evt);
            }
        });
        getContentPane().add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 135, 50));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Statistics", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Old English Text MT", 0, 18))); // NOI18N
        jPanel1.setFocusable(false);
        jPanel1.setInheritsPopupMenu(true);

        lbl1.setText("Player 1 Wins:");

        lbl2.setText("Player 2 Wins:");

        lbl3.setText("Ties:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl3)
                            .addComponent(lbl2))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPlayer2Win)
                            .addComponent(lblTie)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl1)
                        .addGap(74, 74, 74)
                        .addComponent(lblPlayer1Win)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1)
                    .addComponent(lblPlayer1Win))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2)
                    .addComponent(lblPlayer2Win))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl3)
                    .addComponent(lblTie))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 240, 140));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Game Status ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Old English Text MT", 0, 18))); // NOI18N

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtareaGameStatus.setColumns(20);
        txtareaGameStatus.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtareaGameStatus.setRows(5);
        txtareaGameStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(txtareaGameStatus);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 110));

        txtField_11.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        txtField_11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtField_11.setToolTipText("");
        txtField_11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtField_11.setFocusable(false);
        txtField_11.setName("11"); // NOI18N
        txtField_11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLabel_Clicked(evt);
            }
        });
        getContentPane().add(txtField_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 100, 100));

        txtField_10.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        txtField_10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtField_10.setToolTipText("");
        txtField_10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtField_10.setFocusable(false);
        txtField_10.setName("10"); // NOI18N
        txtField_10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLabel_Clicked(evt);
            }
        });
        getContentPane().add(txtField_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 100, 100));

        txtField_01.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        txtField_01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtField_01.setToolTipText("");
        txtField_01.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtField_01.setFocusable(false);
        txtField_01.setName("01"); // NOI18N
        txtField_01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLabel_Clicked(evt);
            }
        });
        getContentPane().add(txtField_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 100, 100));

        txtField_02.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        txtField_02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtField_02.setToolTipText("");
        txtField_02.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtField_02.setFocusable(false);
        txtField_02.setName("02"); // NOI18N
        txtField_02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLabel_Clicked(evt);
            }
        });
        getContentPane().add(txtField_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 100, 100));

        txtField_12.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        txtField_12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtField_12.setToolTipText("");
        txtField_12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtField_12.setFocusable(false);
        txtField_12.setName("12"); // NOI18N
        txtField_12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLabel_Clicked(evt);
            }
        });
        getContentPane().add(txtField_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 100, 100));

        txtField_22.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        txtField_22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtField_22.setToolTipText("");
        txtField_22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtField_22.setFocusable(false);
        txtField_22.setName("22"); // NOI18N
        txtField_22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLabel_Clicked(evt);
            }
        });
        getContentPane().add(txtField_22, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 100, 100));

        txtField_21.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        txtField_21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtField_21.setToolTipText("");
        txtField_21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtField_21.setFocusable(false);
        txtField_21.setName("21"); // NOI18N
        txtField_21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLabel_Clicked(evt);
            }
        });
        getContentPane().add(txtField_21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 100, 100));

        txtField_00.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        txtField_00.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtField_00.setToolTipText("");
        txtField_00.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtField_00.setFocusable(false);
        txtField_00.setName("00"); // NOI18N
        txtField_00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLabel_Clicked(evt);
            }
        });
        getContentPane().add(txtField_00, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 100));

        jTextField3.setBackground(new java.awt.Color(0, 0, 0));
        jTextField3.setText("jTextField1");
        jTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * When txtField is clicked 
     * 1. Gets the location of txtField_Clicked
     * 2. Sets sLocation to have the arrays location in string format
     * 3. Checks to see if game has been started and that the array at current location is empty
     * 4. Checks to see which player is playing
     *      1. If player 1 display "x" and insert "x" into array's location
     *          1. Sets specific color for player 1
     *          2. Checks to see if it's a winning move for player 1
     *              1. If it is increment the score and return false
     *          3. Increment player to switch to player 2's turn
     *      2. If player 2 display "o" and insert "o" into array's location 
     *          1. Sets specific color for player 2
     *          2. Checks to see if it's a winning move for player 2
     *              1. If it is increment the score and return false
     *          3. Decrement player to switch to player 1's turn
     * 5. Check if its a tie
     * 6. GetStatus
     * 7. DisplayScores
     * 8. Highlight Winning Move
     * @param evt 
     */
    private void txtLabel_Clicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLabel_Clicked
        // TODO add your handling code here:
        JTextField MyText = (JTextField)evt.getComponent();
        clsLogic.sLocation = MyText.getName();
        int iRowIndex = Integer.parseInt(clsLogic.sLocation.substring(0,1));
        int iColIndex = Integer.parseInt(clsLogic.sLocation.substring(1,2));
        if((clsLogic.bHasGameStarted == true) && (clsLogic.saBoard[iRowIndex][iColIndex] == "")) {
            switch (clsLogic.iPlayer){
                case 0:
                    MyText.setText("X");
                    clsLogic.saBoard[iRowIndex][iColIndex] = "X";
                    //JOptionPane.showMessageDialog(null, clsLogic.saBoard[iRowIndex][iColIndex]);
                    SetP1TextColor(MyText);
                    if(clsLogic.isWinningMove() == true && clsLogic.iPlayer == 0) {
                        clsLogic.iPlayer1Score++;
                        txtareaGameStatus.setText("Player 1 Wins the game!!");
                        clsLogic.bHasGameStarted = false;
                    }
                    clsLogic.iPlayer++;
                    break;
                case 1:
                    MyText.setText("O");
                    clsLogic.saBoard[iRowIndex][iColIndex] = "O";
                    //JOptionPane.showMessageDialog(null, clsLogic.saBoard[iRowIndex][iColIndex]);    
                    SetP2TextColor(MyText);
                    if(clsLogic.isWinningMove() == true && clsLogic.iPlayer == 1) {
                        clsLogic.iPlayer2Score++;
                        txtareaGameStatus.setText("Player 2 Wins the game!!");
                        clsLogic.bHasGameStarted = false;
                    }
                    clsLogic.iPlayer--;
                    break;           
                }
            if(clsLogic.isTie() == true) {
                clsLogic.iTie = clsLogic.iTie + 1;
                clsLogic.bHasGameStarted = false;
            }
            GameStatus();
            DisplayScores();
            HighlightWinningMove();
        }
    }//GEN-LAST:event_txtLabel_Clicked

    /**
     * Start button - Restarts the board
     * @param evt 
     */
    private void btnStart_Clicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStart_Clicked
        // TODO add your handling code here:
        clsLogic.iPlayer = 0;
        clsLogic.bHasGameStarted = true;
        clsLogic.ClearArray();
        ClearTextField();
        ResetColors();
        GameStatus();
    }//GEN-LAST:event_btnStart_Clicked

    /**
     * Sets a specific color for player 1
     * @param MyText 
     */
    public void SetP1TextColor(JTextField MyText) {
        MyText.setBackground(Color.yellow);
    }
    
    /**
     * Sets a specific color for player 2
     * @param MyText 
     */
    public void SetP2TextColor(JTextField MyText) {
        MyText.setBackground(Color.GREEN);
    }
    
    /**
     * Clears the text fields for the whole board
     */
    public void ClearTextField() {
        txtField_00.setText("");
        txtField_01.setText("");
        txtField_02.setText("");
        //row2
        txtField_10.setText("");
        txtField_11.setText("");
        txtField_12.setText("");
        //row3
        txtField_20.setText("");
        txtField_21.setText("");
        txtField_22.setText("");
    }
    
    /**
     * Resets the color of the text fields to white
     */
    public void ResetColors() {
        //row1 
        txtField_00.setBackground(Color.WHITE);
        txtField_01.setBackground(Color.WHITE);
        txtField_02.setBackground(Color.WHITE);
        //row2
        txtField_10.setBackground(Color.WHITE);
        txtField_11.setBackground(Color.WHITE);
        txtField_12.setBackground(Color.WHITE);
        //row3
        txtField_20.setBackground(Color.WHITE);
        txtField_21.setBackground(Color.WHITE);
        txtField_22.setBackground(Color.WHITE);
    }
    
    /**
     * Highlights the winning move
     */
    public void HighlightWinningMove() {
        if (clsLogic.isWinningMove() == true) {
            switch(clsLogic.eWinningMove){
                case Row1:
                    txtField_00.setBackground(Color.PINK);
                    txtField_01.setBackground(Color.PINK);
                    txtField_02.setBackground(Color.PINK); 
                    break;
                case Row2:
                    txtField_10.setBackground(Color.PINK);
                    txtField_11.setBackground(Color.PINK);
                    txtField_12.setBackground(Color.PINK);
                    break;
                case Row3:
                    txtField_20.setBackground(Color.PINK);
                    txtField_21.setBackground(Color.PINK);
                    txtField_22.setBackground(Color.PINK);
                    break;
                case Col1:
                    txtField_00.setBackground(Color.PINK);
                    txtField_10.setBackground(Color.PINK);
                    txtField_20.setBackground(Color.PINK);
                    break;
                case Col2:
                    txtField_01.setBackground(Color.PINK);
                    txtField_11.setBackground(Color.PINK);
                    txtField_21.setBackground(Color.PINK);
                    break;
                case Col3:
                    txtField_02.setBackground(Color.PINK);
                    txtField_12.setBackground(Color.PINK);
                    txtField_22.setBackground(Color.PINK);
                    break;
                case Diag1:
                    txtField_00.setBackground(Color.PINK);
                    txtField_11.setBackground(Color.PINK);
                    txtField_22.setBackground(Color.PINK);
                    break;
                case Diag2:
                    txtField_02.setBackground(Color.PINK);
                    txtField_11.setBackground(Color.PINK);
                    txtField_20.setBackground(Color.PINK);
                    break;
            }
        }
    }
    
    /**
     * Prints the scores 
     */
    public void DisplayScores() {
        lblPlayer1Win.setText(Integer.toString(clsLogic.iPlayer1Score));
        lblPlayer2Win.setText(Integer.toString(clsLogic.iPlayer2Score));
        lblTie.setText(Integer.toString(clsLogic.iTie));
    }
    
    /**
     * Displays the game status
     */
    public void GameStatus() {
        if (clsLogic.bHasGameStarted == true) {
            switch(clsLogic.iPlayer) {
                case 0:
                    txtareaGameStatus.setText("Player 1 Turn");
                    break;
                case 1: 
                    txtareaGameStatus.setText("Player 2 Turn");
                    break;
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lblPlayer1Win;
    private javax.swing.JLabel lblPlayer2Win;
    private javax.swing.JLabel lblTie;
    private javax.swing.JTextField txtField_00;
    private javax.swing.JTextField txtField_01;
    private javax.swing.JTextField txtField_02;
    private javax.swing.JTextField txtField_10;
    private javax.swing.JTextField txtField_11;
    private javax.swing.JTextField txtField_12;
    private javax.swing.JTextField txtField_20;
    private javax.swing.JTextField txtField_21;
    private javax.swing.JTextField txtField_22;
    private javax.swing.JTextArea txtareaGameStatus;
    // End of variables declaration//GEN-END:variables
}
